### ISSUE TITLE
Avoid img change on mobile (click)

### ISSUE THREAD

**Issue by leandro-andrade-candido** [jwo/react-hover-image#32]
How to disable hover effect on click if device is mobile?

**Comment by jwo** [comment]
I haven’t had to deal with this yet. What would you expect to happen @leandro-andrade-candido ?

**Comment by leandro-andrade-candido** [comment]
When click the img changed also, in mobile/responsive. But.. I don't want
this. I want enable only on hover.

**Comment by jwo** [comment]
I’d probably have a check for device width, and if it’s too small for you, just render a regular image. You can give it style and classnames and should be fine.
